# Generated by Django 4.0.4 on 2022-05-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('number_of_party', models.IntegerField()),
                ('payment', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pos_log',
            },
        ),
        migrations.CreateModel(
            name='PosLogMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menu')),
                ('pos_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_log.poslog')),
            ],
            options={
                'db_table': 'pos_log_menu',
            },
        ),
        migrations.AddField(
            model_name='poslog',
            name='menu',
            field=models.ManyToManyField(related_name='menu', through='pos_log.PosLogMenu', to='menu.menu'),
        ),
        migrations.AddField(
            model_name='poslog',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant'),
        ),
    ]
