# Generated by Django 4.0.4 on 2022-05-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('number_of_party', models.IntegerField()),
                ('payment', models.CharField(max_length=50)),
                ('menu', models.ManyToManyField(related_name='menu', to='menu.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'pos_log',
            },
        ),
    ]
