# Generated by Django 4.0.4 on 2022-05-02 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('menu_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.group')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_name'], name='menu_name_idx'),
        ),
    ]
